dashboard:
  image: ubuntu:latest
  ports:
   - "80:80"
  links:
   - mongo
  environment:
   - MONGO_URL=mongodb://mongo/verja-forum
   - ROOT_URL=http://yverja-forum.com
   - MAIL_URL=smtp://some.mailserver.com:25

mongo:
  image: mongo:latest